[root@cmaster]:/home/caicloud/pgsql/pgcluster# cat Dockerfile
FROM cargo.caicloudprivatetest.com/library/crunchy-postgres:centos7-10.3-1.8.2

USER root
COPY setup.sql /opt/cpm/bin/setup.sql

RUN chown -R postgres:postgres /opt/cpm/
USER 26
